on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: qgxpagamentos/kubectl-set@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG_DATA }}
          kubectl-version: v1.22.5

      - name: Deploy Kubernetes cluster Service/Deployment
        run: |
          kubectl version
          kubectl apply -f manifests/
