on: push
name: deploy
jobs:
  - name: Build and Push
    uses: into-docker/build-action@v3
    with:
      image: target-image:latest
      builder: intodocker/clojure

  - name: Deploy to cluster
    runs-on: ubuntu-latest
    needs: Build and Push
    steps:
      - name: Deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        
      - name: Verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.20"

  - name: Ngrok watcher
    runs-on: ubuntu-latest
    needs: Deploy to cluster
    steps:
      - name: Get ngrok URL
        id: getNgrokUrl
        uses: debianmaster/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.20"
        with:
          args: |
            URL=`kubectl -n prueba get ngrok -o=custom-columns='DATA:status.url' | tail -n1` 
            echo "::set-output name=url::$URL"
