name: Minikube workflow
on: push
jobs:
  minikube:
    name: Start Kubernetes cluster
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Start Minikube
        id: minikube
        uses: hiberbee/github-action-minikube@latest
        with:
          profile: github
                 
      - name: Deploy manifests
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
          kubectl apply -f manifests/deploy.yaml
          kubectl apply -f manifests/service.yaml
          kubectl apply -f manifests/hpa.yaml
        working-directory: ${{ github.workspace }}

      - name: Espera 30 segundos
        run: sleep 30

      - name: Get All Info
        run: kubectl get all
        
      - name: Get metrics info
        run: |
          kubectl -n kube-system get pods
          kubectl top pods        
          
      - name: Get cluster info
        run: kubectl cluster-info
      
        
