on: push
name: deploy
jobs:
  - uses: into-docker/build-action@v3
  with:
    image: target-image:latest
    builder: intodocker/clojure

# optional: push to docker registry
- run: >
    echo ${{ secrets.DOCKER_PASSWORD }} | \
      docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \
      docker push target-image:latest
      
  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        
    - name: verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.20"
        
  ngrok-watcher:
    name: Ngrok watcher
    runs-on: ubuntu-latest
    needs: deploy-to-cluster
    steps:
    - name: Get ngrok URL
      id: getNgrokUrl
      uses: debianmaster/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.20"
      with:
        args: |
          URL=`kubectl -n prueba get ngrok -o=custom-columns='DATA:status.url' | tail -n1` 
          echo "::set-output name=url::$URL"
