name: Kubectl workflow
on: push
jobs:
  kubernetes:
    name: Start Kubernetes cluster
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
          install kubectl: true
                 
      - name: Deploy manifests
        run: |
          kubectl apply -f manifests/deploy.yaml
          kubectl apply -f manifests/service.yaml
          kubectl apply -f manifests/hpa.yaml
        working-directory: ${{ github.workspace }}

      - name: Get All Info
        run: kubectl get all
        
      - name: Get metrics info
        run: |
          kubectl -n kube-system get pods
          kubectl top pods        
          
      - name: Get cluster info
        run: kubectl cluster-info
      
        
