name: Kubernetes Deploy

on:
  push:
    branches:
      - main

#env:
 # KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      - name: Use context
        run: kubectl config use-context minikube  

      - name: Deploy App(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply manifests/deploy.yml
          
      - name: Deploy Service
        uses: actions-hub/kubectl@master
        with:
          args: apply manifests/service.yml
