name: Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Reemplazar con la versión correcta
        
      - name: Set up kubectl
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}  # Reemplazar con el nombre del secreto que contiene tu configuración kubeconfig
          method: kubeconfig

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ChallengeDevOps/tree/main/manifests/.
